-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys
import Leanactors.Term

namespace Leanactors.Fixtures.AssignChain

open Leanactors


inductive Msg
  | now_playing (a0 : Option Term)
  | listeners (a0 : Term)
  deriving Repr, DecidableEq

inductive St
  | tuner (now_playing : Option Term) (playing : Bool) (listeners : Term) (busy : Term)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .tuner _ _ _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .now_playing none

def beh : EBehavior St Msg
  | _, _, .tuner _ _ listeners busy, .now_playing track => (.tuner track (track ≠ none) listeners busy, [])
  | _, _, .tuner now_playing playing _ _, .listeners n => (.tuner now_playing playing n n, [])

end Leanactors.Fixtures.AssignChain

