-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.Booleans

open Leanactors


inductive Msg
  | flip
  | set (a0 : Bool)
  | bump
  | other
  deriving Repr, DecidableEq

inductive St
  | flag (f0 : Bool) (f1 : Nat)
  | other (s : Bool)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .flag _ _ => false
    | .other _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .flip

def beh : EBehavior St Msg
  | _, _, .flag true n, .flip => (.flag false n, [])
  | _, _, .flag false n, .flip => (.flag true n, [])
  | _, _, .flag _w0 n, .set b => (.flag b n, [])
  | _, _, .flag on n, .bump => if on then (.flag on (n + 1), []) else if (n > 0) then (.flag on (n - 1), []) else (.flag true 0, [])
  | _, _, .other b, .other => (.other b, [])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.Booleans

