-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Core

namespace Leanactors.Fixtures.Booleans

open Leanactors


inductive Msg
  | flip
  | set (a0 : Bool)
  | bump
  | other
  deriving Repr, DecidableEq

inductive St
  | flag (f0 : Bool) (f1 : Nat)
  | other (s : Bool)
  deriving Repr, DecidableEq


def beh : Behavior St Msg
  | _, .flag true n, .flip => (.flag false n, [])
  | _, .flag false n, .flip => (.flag true n, [])
  | _, .flag _w0 n, .set b => (.flag b n, [])
  | _, .flag on n, .bump => if on then (.flag on (n + 1), []) else if (n > 0) then (.flag on (n - 1), []) else (.flag true 0, [])
  | _, .other b, .other => (.other b, [])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, s, _ => (s, [])

end Leanactors.Fixtures.Booleans

