-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.CallPatternLhs

open Leanactors

inductive Reply
  | ok
  | denied
  deriving Repr, DecidableEq

inductive Msg
  | open
  | enter (caller : Pid)
  | reply (a0 : Reply)
  | try
  deriving Repr, DecidableEq

inductive St
  | gate (s : Bool)
  | visitor (s : Nat)
  | visitor_await0 (n : Nat)
  deriving Repr, DecidableEq

/-- Registered name `Gate`. -/
def gate : Pid := 0

/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .gate _ => false
    | .visitor _ => false
    | .visitor_await0 _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .open

def beh : EBehavior St Msg
  | _, _, .gate _w0, .open => (.gate true, [])
  | _, _, .gate true, .enter from_ => (.gate true, [.send from_ (.reply .ok)])
  | _, _, .gate false, .enter from_ => (.gate false, [.send from_ (.reply .denied)])
  | me, _, .visitor n, .try => (.visitor_await0 n, [.send gate (.enter me)])
  | _, _, .visitor_await0 n, .reply .ok => (.visitor (n + 1), [])
  | me, _, .visitor_await0 n, m => (.visitor_await0 n, [.send me m])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.CallPatternLhs

