-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Core

namespace Leanactors.Fixtures.CallPatternLhs

open Leanactors

inductive Reply
  | ok
  | denied
  deriving Repr, DecidableEq

inductive Msg
  | open
  | enter (caller : Pid)
  | reply (a0 : Reply)
  | try
  deriving Repr, DecidableEq

inductive St
  | gate (s : Bool)
  | visitor (s : Nat)
  | visitor_await0 (n : Nat)
  deriving Repr, DecidableEq

/-- Registered name `Gate`. -/
def gate : Pid := 0

def beh : Behavior St Msg
  | _, .gate _w0, .open => (.gate true, [])
  | _, .gate true, .enter from_ => (.gate true, [(from_, .reply .ok)])
  | _, .gate false, .enter from_ => (.gate false, [(from_, .reply .denied)])
  | me, .visitor n, .try => (.visitor_await0 n, [(gate, .enter me)])
  | _, .visitor_await0 n, .reply .ok => (.visitor (n + 1), [])
  | me, .visitor_await0 n, m => (.visitor_await0 n, [(me, m)])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, s, _ => (s, [])

end Leanactors.Fixtures.CallPatternLhs

