-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.CaseIf

open Leanactors

inductive Colour
  | red
  | amber
  | green
  deriving Repr, DecidableEq

inductive Msg
  | next
  | force (a0 : Colour)
  deriving Repr, DecidableEq

inductive St
  | light (f0 : Colour) (f1 : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .light _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .next

def beh : EBehavior St Msg
  | _, _, .light c n, .next => (match c with | .red => (.light .green (n + 1), []) | .green => (.light .amber n, []) | .amber => (.light .red n, []))
  | _, _, .light _w0 n, .force c => if (n > 3) then (.light c 0, []) else (.light c (n + 1), [])

end Leanactors.Fixtures.CaseIf

