-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Core

namespace Leanactors.Fixtures.CaseIf

open Leanactors

inductive Colour
  | red
  | amber
  | green
  deriving Repr, DecidableEq

inductive Msg
  | next
  | force (a0 : Colour)
  deriving Repr, DecidableEq

inductive St
  | light (f0 : Colour) (f1 : Nat)
  deriving Repr, DecidableEq


def beh : Behavior St Msg
  | _, .light c n, .next => (match c with | .red => (.light .green (n + 1), []) | .green => (.light .amber n, []) | .amber => (.light .red n, []))
  | _, .light _w0 n, .force c => if (n > 3) then (.light c 0, []) else (.light c (n + 1), [])

end Leanactors.Fixtures.CaseIf

