-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys
import Leanactors.Time

namespace Leanactors.Fixtures.Clock

open Leanactors

inductive Reply
  | at (a0 : Instant)
  | n (a0 : Nat)
  deriving Repr, DecidableEq

inductive Msg
  | touch
  | mono
  | last (caller : Pid)
  | hits (caller : Pid)
  | reply (a0 : Reply)
  deriving Repr, DecidableEq

inductive St
  | ticker (last : Instant) (started : Instant) (hits : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .ticker _ _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .touch

def beh : EBehavior St Msg
  | _, _, .ticker _ started hits, .touch => (.ticker Instant.now started (hits + 1), [])
  | _, _, .ticker _ started hits, .mono => (.ticker Instant.now started hits, [])
  | _, _, .ticker last started hits, .last from_ => (.ticker last started hits, [.send from_ (.reply (.at last))])
  | _, _, .ticker last started hits, .hits from_ => (.ticker last started hits, [.send from_ (.reply (.n hits))])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.Clock

