-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.ControlExpr

open Leanactors

inductive Level
  | low
  | mid
  | high
  deriving Repr, DecidableEq

inductive Msg
  | set (a0 : Int)
  | adjust (a0 : Int)
  | tick
  | classify
  deriving Repr, DecidableEq

inductive St
  | gauge (f0 : Int) (f1 : Level)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .gauge _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .tick

def beh : EBehavior St Msg
  | _, _, .gauge _ l, .set v => (.gauge v (if (v > 10) then .high else l), [])
  | _, _, .gauge v l, .adjust d => (let n := (match l with | .low => (v + d) | .mid => (match d with | 0 => v | _w0 => (v + (2 * d))) | .high => (v - d)); (.gauge n l, []))
  | _, _, .gauge v _, .tick => (.gauge v (if (v > 10) then .high else (if (v > 0) then .mid else .low)), [])
  | _, _, .gauge v _, .classify => (.gauge (let w := (v * 2); (w - 1)) .mid, [])

end Leanactors.Fixtures.ControlExpr

