-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.Continue

open Leanactors

inductive Reply
  | ok
  deriving Repr, DecidableEq

inductive Msg
  | load (a0 : Nat)
  | refresh
  | reset
  | tick
  | timeout
  | loaded (a0 : Nat)
  | reload (caller : Pid)
  | reply (a0 : Reply)
  deriving Repr, DecidableEq

inductive St
  | loader (f0 : Nat) (f1 : Pid)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .loader _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .refresh

def beh : EBehavior St Msg
  | _, _, .loader n sub, .load k => if ((n + k) > 10) then (.loader 0 sub, [.send sub (.loaded k), .send sub (.loaded (n + k))]) else (.loader ((n + k) + 1) sub, [.send sub (.loaded k)])
  | _, _, .loader s_0 s_1, .refresh => if (s_0 > 10) then (.loader 0 s_1, [.send s_1 (.loaded s_0)]) else (.loader (s_0 + 1) s_1, [])
  | _, _, .loader _ s_1, .reset => (.loader 0 s_1, [])
  | me, _, .loader s_0 s_1, .tick => (.loader s_0 s_1, [.sendAfter me .timeout])
  | _, _, .loader n sub, .reload from_ => if ((n + 1) > 10) then (.loader 0 sub, [.send sub (.loaded 0), .send from_ (.reply .ok), .send sub (.loaded (n + 1))]) else (.loader ((n + 1) + 1) sub, [.send sub (.loaded 0), .send from_ (.reply .ok)])
  | _, _, .loader s_0 s_1, .timeout => (.loader s_0 s_1, [])
  | _, _, .loader n sub, .loaded m => (.loader (n + m) sub, [])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.Continue

