-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.CrashGuard

open Leanactors


inductive Msg
  | withdraw (a0 : Nat)
  | quit
  deriving Repr, DecidableEq

inductive St
  | vault (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .vault _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .quit

def beh : EBehavior St Msg
  | _, _, .vault b, .withdraw n => if (n ≤ b) then (.vault (b - n), []) else (.vault b, [.exit .error])
  | _, _, .vault b, .quit => (.vault b, [.exit .normal])

end Leanactors.Fixtures.CrashGuard

