-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.CrashUncovered

open Leanactors


inductive Msg
  | open
  | close
  | quit
  deriving Repr, DecidableEq

inductive St
  | door (s : Bool)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .door _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .open

def beh : EBehavior St Msg
  | _, _, .door false, .open => (.door true, [])
  | _, _, .door _w0, .close => (.door false, [])
  | _, _, .door s_0, .open => (.door s_0, [.exit .error])
  | _, _, .door s, .quit => (.door s, [.exit .normal])

end Leanactors.Fixtures.CrashUncovered

