-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.DefpLoop

open Leanactors


inductive Msg
  | add (a0 : Nat)
  | stop
  deriving Repr, DecidableEq

inductive St
  | counter (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .counter _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .stop

def beh : EBehavior St Msg
  | _, _, .counter n, .add k => (.counter (n + k), [])
  | _, _, .counter n, .stop => (.counter n, [.exit .normal])

end Leanactors.Fixtures.DefpLoop

