-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.DownExit

open Leanactors


inductive Msg
  | start
  | EXIT (a0 : Pid) (a1 : Reason)
  | DOWN (a0 : Pid) (a1 : Reason)
  | crash
  | bye
  deriving Repr, DecidableEq

inductive St
  | nanny (f0 : Option Pid) (f1 : Option Pid)
  | kid (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .nanny _ _ => true
    | .kid _ => false
  exitMsg := fun p r => .EXIT p r
  downMsg := some fun p r => .DOWN p r

def beh : EBehavior St Msg
  | _, fresh, .nanny none none, .start => (.nanny (some fresh) (some (fresh + 1)), [.spawnLink (.kid 0), .spawn (.kid 1), .monitor (fresh + 1)])
  | _, _, .nanny (some a') b, .EXIT a _ => if a = a' then (.nanny none b, []) else (.nanny (some a') b, [])
  | _, _, .nanny a (some b'), .DOWN b _ => if b = b' then (.nanny a none, []) else (.nanny a (some b'), [])
  | _, _, .nanny s_0 s_1, _ => (.nanny s_0 s_1, [])
  | _, _, .kid n, .crash => (.kid n, [.exit .error])
  | _, _, .kid n, .bye => (.kid n, [.exit .normal])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.DownExit

