-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.EffectBeforeBranch

open Leanactors


inductive Msg
  | route (a0 : Nat)
  | grow (a0 : Nat)
  | ping
  deriving Repr, DecidableEq

inductive St
  | router (f0 : Option Pid) (f1 : Nat)
  | sink (s : Nat)
  | worker (s : Nat)
  deriving Repr, DecidableEq

/-- Registered name `Sink`. -/
def sink : Pid := 0

/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .router _ _ => false
    | .sink _ => false
    | .worker _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .ping

def beh : EBehavior St Msg
  | _, _, .router peer n, .route k => if (k > n) then (.router peer k, [.send sink .ping]) else (.router peer n, [.send sink .ping])
  | _, fresh, .router peer n, .grow k => (let total := (n + k); (match peer with | none => (.router (some (fresh + 1)) total, [.spawn (.worker total), .spawn (.worker total), .send (fresh + 1) .ping]) | (some p) => (.router (some fresh) total, [.spawn (.worker total), .send p .ping])))
  | _, _, .router s_0 s_1, .ping => (.router s_0 s_1, [])
  | _, _, .sink n, .ping => (.sink (n + 1), [])
  | _, _, .worker n, .ping => (.worker (n + 1), [])
  | me, _, .worker s_0, m => (.worker s_0, [.send me m])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.EffectBeforeBranch

