-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.EnumSplit

open Leanactors

inductive Phase
  | idle
  | busy
  deriving Repr, DecidableEq

inductive Msg
  | go
  | pop
  | push (a0 : Nat)
  deriving Repr, DecidableEq

inductive St
  | machine (f0 : Phase) (f1 : List Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .machine _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .go

def beh : EBehavior St Msg
  | _, _, .machine .idle q, .go => (.machine .busy q, [])
  | _, _, .machine .busy q, .go => (.machine .idle q, [])
  | _, _, .machine ph [], .pop => (.machine ph [], [])
  | _, _, .machine ph (_w0 :: t), .pop => (.machine ph t, [])
  | _, _, .machine ph q, .push n => (.machine ph (q ++ [n]), [])

end Leanactors.Fixtures.EnumSplit

