-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.EnumList

open Leanactors

inductive Kind
  | small
  | big
  deriving Repr, DecidableEq

structure Item where
  kind : Kind := .small
  size : Nat := 0
  deriving Repr, DecidableEq

inductive Reply
  | items (a0 : List Item)
  | sizes (a0 : List Nat)
  | n (a0 : Nat)
  | one (a0 : Item)
  | none
  deriving Repr, DecidableEq

inductive Msg
  | add (a0 : Item)
  | drop_first
  | flip
  | of_kind (caller : Pid) (a1 : Kind)
  | sizes (caller : Pid)
  | biggest (caller : Pid)
  | summary (caller : Pid)
  | third (caller : Pid)
  | reply (a0 : Reply)
  deriving Repr, DecidableEq

inductive St
  | shelf (s : List Item)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .shelf _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .drop_first

def beh : EBehavior St Msg
  | _, _, .shelf l, .add it => (.shelf (l ++ [it]), [])
  | _, _, .shelf l, .drop_first => (.shelf (List.tail l), [])
  | _, _, .shelf l, .flip => (.shelf (List.reverse l), [])
  | _, _, .shelf l, .of_kind from_ k => (.shelf l, [.send from_ (.reply (.items (List.filter (fun x1 => (x1.kind = k)) l)))])
  | _, _, .shelf l, .sizes from_ => (.shelf l, [.send from_ (.reply (.sizes (List.map (fun it => it.size) l)))])
  | _, _, .shelf l, .summary from_ => (let big := List.map (fun it => it.size) (List.filter (fun it => (it.size > 2)) l); let small := List.filter (fun x1 => !((x1.size > 2))) l; let n := List.length (List.filter (fun it => (it.kind = .big)) l); if (List.any l (fun x1 => (x1.size > 5)) ∧ List.all small (fun x1 => (x1.size ≤ 2))) then (.shelf l, [.send from_ (.reply (.sizes (big ++ List.take 1 big)))]) else (.shelf l, [.send from_ (.reply (.n ((n + List.length small) + List.length l)))]))
  | _, _, .shelf l, .biggest from_ => if (List.isEmpty l ∨ (({} : Item) ∈ l)) then (.shelf l, [.send from_ (.reply .none)]) else (.shelf l, [.send from_ (.reply (.one (List.headD (List.drop 1 l) ({} : Item))))])
  | _, _, .shelf l, .third from_ => (match l[2]? with | none => (.shelf l, [.send from_ (.reply .none)]) | (some it) => (.shelf l, [.send from_ (.reply (.one it))]))
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.EnumList

