-- GENERATED by elixir/to_lean.exs. Do not edit.
-- Not translated (public API, not a callback): Tables.open/1, Tables.close/1, Tables.open!/1
import Leanactors.Sys
import Leanactors.AssocList
import Leanactors.Term

namespace Leanactors.Fixtures.EtsResource

open Leanactors

inductive Reply
  | ok1 (a0 : Term)
  | error
  | ok
  deriving Repr, DecidableEq

inductive Msg
  | drop (a0 : Term)
  | open (caller : Pid) (a1 : Term)
  | pair (caller : Pid) (a1 : Term)
  | close (caller : Pid) (a1 : Term)
  | reply (a0 : Reply)
  deriving Repr, DecidableEq

inductive St
  | tables (refs : List (Term × Term)) (ets : Nat)
  deriving Repr, DecidableEq

/-- Registered name `Tables`. -/
def tables : Pid := 0

/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .tables _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .drop (Term.mk 0)

def beh : EBehavior St Msg
  | _, _, .tables refs ets, .open from_ name => (.tables (AssocList.insert refs name (Term.mk ets)) (ets + 1), [.send from_ (.reply (.ok1 (Term.mk ets)))])
  | _, _, .tables refs ets, .pair from_ name => (.tables (AssocList.insert (AssocList.insert refs name (Term.mk ets)) name (Term.mk (ets + 1))) (ets + 2), [.send from_ (.reply (.ok1 (Term.mk (ets + 1))))])
  | _, _, .tables refs ets, .close from_ name => (match AssocList.get? refs name with | none => (.tables refs ets, [.send from_ (.reply .error)]) | (some _) => (.tables (AssocList.erase refs name) ets, [.send from_ (.reply .ok)]))
  | _, _, .tables refs ets, .drop name => (match AssocList.get? refs name with | none => (.tables refs ets, []) | (some _) => (.tables (AssocList.erase refs name) ets, []))
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.EtsResource

