-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.GuardDefer

open Leanactors


inductive Msg
  | take (a0 : Nat)
  | put (a0 : Nat)
  deriving Repr, DecidableEq

inductive St
  | pool (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .pool _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .take 0

def beh : EBehavior St Msg
  | me, _, .pool n, m@(.take k) => if (k ≤ n) then (.pool (n - k), []) else (.pool n, [.send me m])
  | _, _, .pool n, .put k => (.pool (n + k), [])

end Leanactors.Fixtures.GuardDefer

