-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Core

namespace Leanactors.Fixtures.GuardFallthrough

open Leanactors


inductive Msg
  | withdraw (a0 : Nat)
  | reset
  deriving Repr, DecidableEq

inductive St
  | acct (s : Int)
  deriving Repr, DecidableEq


def beh : Behavior St Msg
  | _, .acct b, .withdraw n => if (n ≤ b) then (.acct (b - n), []) else (.acct b, [])
  | _, .acct _w0, .reset => (.acct 0, [])

end Leanactors.Fixtures.GuardFallthrough

