-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.GuardFallthrough

open Leanactors


inductive Msg
  | withdraw (a0 : Nat)
  | reset
  deriving Repr, DecidableEq

inductive St
  | acct (s : Int)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .acct _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .reset

def beh : EBehavior St Msg
  | _, _, .acct b, .withdraw n => if (n ≤ b) then (.acct (b - n), []) else (.acct b, [])
  | _, _, .acct _w0, .reset => (.acct 0, [])

end Leanactors.Fixtures.GuardFallthrough

