-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.InitTuple

open Leanactors


inductive Msg
  | go
  | done (a0 : Nat)
  | run
  deriving Repr, DecidableEq

inductive St
  | parent (f0 : Option Pid) (f1 : Nat)
  | child (f0 : Pid) (f1 : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .parent _ _ => false
    | .child _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .go

def beh : EBehavior St Msg
  | me, fresh, .parent none r, .go => (.parent (some fresh) r, [.spawn (.child me (3 + 1))])
  | _, _, .parent _w0 r, .done v => (.parent none (r + v), [])
  | _, _, .parent s_0 s_1, _ => (.parent s_0 s_1, [])
  | _, _, .child parent n, .run => (.child parent n, [.send parent (.done n), .exit .normal])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.InitTuple

