-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.InitStmts

open Leanactors


inductive Msg
  | EXIT (a0 : Pid) (a1 : Reason)
  | drain
  | go
  deriving Repr, DecidableEq

inductive St
  | pool (f0 : Nat) (f1 : Nat)
  | boot (s : Option Pid)
  deriving Repr, DecidableEq


/-- `Pool.headroom/2` -/
def pool_headroom (size : Nat) (slack : Nat) : Nat :=
  (size + slack)

/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .pool _ _ => true
    | .boot _ => false
  exitMsg := fun p r => .EXIT p r

def beh : EBehavior St Msg
  | _, _, .pool cap _, .drain => (.pool cap 0, [])
  | _, _, .pool cap used, .EXIT _ _ => (.pool cap (used - 1), [])
  | _, fresh, .boot _, .go => (.boot (some fresh), [.spawnLink (.pool (pool_headroom 4 1) 0)])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.InitStmts

