-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.IsBinaryString

open Leanactors


inductive Msg
  | note (a0 : String)
  | count (a0 : Nat)
  | kinds (caller : Pid)
  | reply (a0 : Nat)
  deriving Repr, DecidableEq

inductive St
  | sniffer (label : String) (n : Nat) (tag : Option Pid)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .sniffer _ _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .note ""

def beh : EBehavior St Msg
  | _, _, .sniffer label n tag, .note x => if true then (.sniffer x n tag, []) else (.sniffer label n tag, [])
  | _, _, .sniffer label n tag, .count k => if false then (.sniffer label n tag, []) else (.sniffer label (n + k) tag, [])
  | _, _, .sniffer label n tag, .kinds from_ => (let bad := (((false ∨ false) ∨ false) ∨ false); if bad then (.sniffer label n tag, [.send from_ (.reply 0)]) else (.sniffer label n tag, [.send from_ (.reply n)]))
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.IsBinaryString

