-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.KernelGuards

open Leanactors


inductive Msg
  | watch (a0 : Pid)
  | clear
  | scale (a0 : Nat)
  | pick (a0 : Nat)
  | count (caller : Pid)
  | reply (a0 : Nat)
  deriving Repr, DecidableEq

inductive St
  | probe (f0 : Option Pid) (f1 : List Nat) (f2 : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .probe _ _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .clear

def beh : EBehavior St Msg
  | _, _, .probe owner l n, .watch p => if (owner.isNone ∧ true) then (.probe (some p) l n, []) else (.probe owner l n, [])
  | _, _, .probe owner l n, .clear => if ((((((true ∨ false) ∧ (¬ false)) ∧ true) ∧ true) ∧ (¬ false)) ∧ (¬ false)) then (.probe owner [] n, []) else (.probe owner l n, [])
  | _, _, .probe owner l n, .scale k => (let m := (min (max (n * k) 1) 100); (.probe owner l (((m / 2) + (m % 3)) + n), []))
  | _, _, .probe owner l n, .pick k => if ((k ∈ l) ∧ (k ≠ n)) then (.probe owner l k, []) else (.probe owner l n, [])
  | _, _, .probe owner l n, .count from_ => (.probe owner l n, [.send from_ (.reply (List.length l + n))])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.KernelGuards

