-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.KeywordVar

open Leanactors


inductive Msg
  | hello (a0 : Pid)
  | move (a0 : Nat)
  | set (a0 : Bool)
  | whoami (caller : Pid)
  | reply (a0 : Pid)
  deriving Repr, DecidableEq

inductive St
  | echo (f0 : Option Pid) (f1 : Nat) (f2 : Bool)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .echo _ _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun p _ => .hello p

def beh : EBehavior St Msg
  | me, _, .echo f at_ open_, .hello from_ => (.echo f at_ open_, [.send from_ (.hello me)])
  | _, _, .echo f _w0 open_, .move at_ => (.echo f at_ open_, [])
  | _, _, .echo f at_ _w0, .set open_ => (.echo f at_ open_, [])
  | me, _, .echo _w0 at_ open_, .whoami from_ => (.echo (some from_) at_ open_, [.send from_ (.reply me)])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.KeywordVar

