-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys
import Leanactors.AssocList

namespace Leanactors.Fixtures.KeywordOpts

open Leanactors

-- The atoms this file uses as keyword-list keys.
inductive Atom
  | retries
  | timeout
  deriving Repr, DecidableEq

inductive Msg
  | set (a0 : List (Atom × Nat))
  | put (a0 : Atom) (a1 : Nat)
  | drop (a0 : Atom)
  | defaults
  | retries (caller : Pid)
  | timeout (caller : Pid)
  | must (caller : Pid)
  | reply (a0 : Nat)
  deriving Repr, DecidableEq

inductive St
  | limits (s : List (Atom × Nat))
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .limits _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .defaults

def beh : EBehavior St Msg
  | _, _, .limits _w0, .set o => (.limits o, [])
  | _, _, .limits opts, .put k v => (.limits (AssocList.insert opts k v), [])
  | _, _, .limits opts, .drop k => (.limits (AssocList.erase opts k), [])
  | _, _, .limits _w0, .defaults => (.limits [(.retries, 3), (.timeout, 5000)], [])
  | _, _, .limits opts, .retries from_ => (.limits opts, [.send from_ (.reply ((AssocList.get? opts .retries).getD 0))])
  | _, _, .limits opts, .must from_ => (.limits opts, [.send from_ (.reply ((AssocList.get? opts .retries).getD 0))])
  | _, _, .limits opts, .timeout from_ => (match AssocList.get? opts .timeout with | none => (.limits opts, [.send from_ (.reply 0)]) | (some t) => (.limits opts, [.send from_ (.reply t)]))
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.KeywordOpts

