-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.KindCastUncovered

open Leanactors


inductive Msg
  | tick
  | bump
  | set (a0 : Nat)
  deriving Repr, DecidableEq

inductive St
  | counter (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .counter _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .tick

def beh : EBehavior St Msg
  | _, _, .counter _w0, .set v => (.counter v, [])
  | _, _, .counter s_0, .bump => (.counter s_0, [.exit .error])
  | _, _, .counter n, .tick => (.counter (n + 1), [])

end Leanactors.Fixtures.KindCastUncovered

