-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.KindInfoUncovered

open Leanactors


inductive Msg
  | set (a0 : Nat)
  | tick
  | stale
  deriving Repr, DecidableEq

inductive St
  | ticker (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .ticker _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .tick

def beh : EBehavior St Msg
  | _, _, .ticker _w0, .set v => (.ticker v, [])
  | _, _, .ticker n, .tick => (.ticker (n + 1), [])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.KindInfoUncovered

