-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys
import Leanactors.AssocList

namespace Leanactors.Fixtures.LetBindings

open Leanactors


inductive Msg
  | bump
  | first
  | widen
  | size (caller : Pid)
  | reply (a0 : Nat)
  deriving Repr, DecidableEq

inductive St
  | entries (s : List (Nat × Nat))
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .entries _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .bump

def beh : EBehavior St Msg
  | _, _, .entries m, .bump => (let d := 2; (.entries (AssocList.insert m 0 (let base := (AssocList.get? m 0).getD 0; (base + d))), []))
  | _, _, .entries m, .first => (match m[0]? with | none => (.entries m, []) | (some e) => (let (k, v) := e; (.entries (AssocList.insert m k (v + 1)), [])))
  | _, _, .entries m, .widen => (match m[0]? with | none => (.entries m, []) | (some e) => (.entries (AssocList.insert m e.1 (e.2 * 2)), []))
  | _, _, .entries m, .size from_ => (.entries m, [.send from_ (.reply (AssocList.size m))])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.LetBindings

