-- GENERATED by elixir/to_lean.exs. Do not edit.
-- Not translated (public API, not a callback): Board.mount/3
-- Not translated (a LiveView browser event is not a message, but it IS a transition of the real process, which this model does not carry): Board.handle_event/3
import Leanactors.Sys
import Leanactors.Term

namespace Leanactors.Fixtures.LiveviewAssigns

open Leanactors


inductive Msg
  | entry (a0 : Term)
  | reset
  deriving Repr, DecidableEq

inductive St
  | board (entries : List Term) (count : Int) (last : Term)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .board _ _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .reset

def beh : EBehavior St Msg
  | _, _, .board entries count _, .entry e => (.board (entries ++ [e]) (count + 1) e, [])
  | _, _, .board _ _ last, .reset => (.board [] 0 last, [])

end Leanactors.Fixtures.LiveviewAssigns

