-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.LocalRecursion

open Leanactors


inductive Msg
  | push (a0 : Nat)
  | total (caller : Pid)
  | steps (caller : Pid)
  | reply (a0 : Nat)
  deriving Repr, DecidableEq

inductive St
  | tally (s : List Nat)
  deriving Repr, DecidableEq

/-- Registered name `Tally`. -/
def tally : Pid := 0

/-- Fuel for the local helpers whose recursion Lean does not see as structural.
    A call that would need more than `localFuel` steps returns the default
    value of its result type, so such a helper models the Elixir function only up
    to that depth. -/
def localFuel : Nat := 64

/-- `Tally.since/1` -/
def tally_since (fuel : Nat) (a0 : Nat) : Nat :=
  match fuel with | 0 => 0 | fuel + 1 => (match a0 with | 0 => 0 | n => (1 + tally_since fuel (n - 1)))

/-- `Tally.total/1` -/
def tally_total (a0 : List Nat) : Nat :=
  match a0 with | [] => 0 | (h :: t) => (h + tally_total t)

/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .tally _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .push 0

def beh : EBehavior St Msg
  | _, _, .tally l, .push k => (.tally (l ++ [k]), [])
  | _, _, .tally l, .total from_ => (.tally l, [.send from_ (.reply (tally_total l))])
  | _, _, .tally l, .steps from_ => (.tally l, [.send from_ (.reply (tally_since localFuel (List.length l)))])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.LocalRecursion

