-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.LocalHelper

open Leanactors

inductive Level
  | empty
  | low
  | full
  deriving Repr, DecidableEq

inductive Msg
  | take (a0 : Nat)
  | put (a0 : Nat)
  | restock
  | level (caller : Pid)
  | reply (a0 : Level)
  deriving Repr, DecidableEq

inductive St
  | shelf (s : Nat)
  deriving Repr, DecidableEq

/-- Registered name `Shelf`. -/
def shelf : Pid := 0

/-- `Shelf.clamp/1` -/
def shelf_clamp (n : Nat) : Nat :=
  (if (n > 10) then 10 else n)

/-- `Shelf.label/1` -/
def shelf_label (n : Nat) : Level :=
  (if (n = 0) then .empty else (if (n < 3) then .low else .full))

/-- `Shelf.min_of/2` -/
def shelf_min_of (a : Nat) (b : Nat) : Nat :=
  (if (a ≤ b) then a else b)

/-- `Shelf.restock/2` -/
def shelf_restock (n : Nat) (by_ : Nat) : Nat :=
  (let room := (10 - n); shelf_clamp (n + shelf_min_of by_ room))

/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .shelf _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .restock

def beh : EBehavior St Msg
  | _, _, .shelf n, .take k => (.shelf (n - k), [])
  | _, _, .shelf n, .put k => (.shelf (shelf_clamp (n + k)), [])
  | _, _, .shelf n, .restock => (.shelf (shelf_restock n 4), [])
  | _, _, .shelf n, .level from_ => (.shelf n, [.send from_ (.reply (shelf_label n))])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.LocalHelper

