-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.LoggerNoop

open Leanactors


inductive Msg
  | add (a0 : Nat)
  | reset
  deriving Repr, DecidableEq

inductive St
  | chatty (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .chatty _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .reset

def beh : EBehavior St Msg
  | _, _, .chatty n, .add k => (.chatty (n + k), [])
  | _, _, .chatty _n, .reset => (.chatty 0, [])

end Leanactors.Fixtures.LoggerNoop

