-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys
import Leanactors.SetList

namespace Leanactors.Fixtures.Mapset

open Leanactors

inductive Item
  | a
  | b
  | c
  deriving Repr, DecidableEq

inductive Reply
  | yes (a0 : Bool)
  | n (a0 : Nat)
  | items (a0 : List Item)
  deriving Repr, DecidableEq

inductive Msg
  | see (a0 : Item)
  | forget (a0 : Item)
  | merge (a0 : List Item)
  | clear
  | seen? (caller : Pid) (a1 : Item)
  | count (caller : Pid)
  | list (caller : Pid)
  | reply (a0 : Reply)
  deriving Repr, DecidableEq

inductive St
  | seen (s : List Item)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .seen _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .clear

def beh : EBehavior St Msg
  | _, _, .seen s, .see i => (.seen (SetList.insert s i), [])
  | _, _, .seen s, .forget i => (.seen (SetList.erase s i), [])
  | _, _, .seen s, .merge o => (.seen (SetList.union s o), [])
  | _, _, .seen _w0, .clear => (.seen [], [])
  | _, _, .seen s, .seen? from_ i => (.seen s, [.send from_ (.reply (.yes (SetList.contains s i)))])
  | _, _, .seen s, .count from_ => (.seen s, [.send from_ (.reply (.n (SetList.size s)))])
  | _, _, .seen s, .list from_ => (.seen s, [.send from_ (.reply (.items (SetList.toList s)))])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.Mapset

