-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys
import Leanactors.AssocList

namespace Leanactors.Fixtures.Maps

open Leanactors

inductive Key
  | x
  | y
  deriving Repr, DecidableEq

inductive Msg
  | incr (a0 : Key)
  | drop (a0 : Key)
  | copy_x (a0 : Key)
  | zero
  | reset
  | prune
  | count (caller : Pid) (a1 : Key)
  | size (caller : Pid)
  | reply (a0 : Nat)
  deriving Repr, DecidableEq

inductive St
  | counts (s : List (Key × Nat))
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .counts _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .zero

def beh : EBehavior St Msg
  | _, _, .counts m, .incr k => if AssocList.hasKey m k then (.counts (AssocList.insert m k ((AssocList.get? m k).getD 0 + 1)), []) else (.counts (AssocList.insert m k 1), [])
  | _, _, .counts m, .drop k => (match AssocList.get? m k with | (some 1) => (.counts (AssocList.erase m k), []) | (some n) => (.counts (AssocList.insert m k (n - 1)), []) | none => (.counts m, []))
  | _, _, .counts m, .copy_x k => (match AssocList.get? m .x with | some v => (.counts (AssocList.insert m k v), []) | none => (.counts m, []))
  | _, _, .counts _w0, .zero => (.counts [(.x, 0), (.y, 0)], [])
  | _, _, .counts m, .reset => if AssocList.get? m .x = some 0 ∧ AssocList.hasKey m .y then (.counts (AssocList.erase m .y), []) else (.counts [], [])
  | _, _, .counts m, .prune => if (AssocList.size m > 1) then (.counts (AssocList.reject m (fun (_k, n) => (n = 0))), []) else (.counts m, [])
  | _, _, .counts m, .count from_ k => (match AssocList.get? m k with | none => (.counts m, [.send from_ (.reply 0)]) | (some n) => (.counts m, [.send from_ (.reply n)]))
  | _, _, .counts m, .size from_ => (.counts m, [.send from_ (.reply (AssocList.size m))])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.Maps

