-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.ModuleValue

open Leanactors

-- The module names this file uses as values.
inductive Module
  | Fallback
  | Loom_MCP_Client
  deriving Repr, DecidableEq

inductive Msg
  | route (a0 : Module)
  | reset
  | deep
  | impl (caller : Pid)
  | reply (a0 : Module)
  deriving Repr, DecidableEq

inductive St
  | router (s : Module)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .router _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .reset

def beh : EBehavior St Msg
  | _, _, .router _w0, .route m => (.router m, [])
  | _, _, .router _w0, .reset => (.router .Fallback, [])
  | _, _, .router _w0, .deep => (.router .Loom_MCP_Client, [])
  | _, _, .router m, .impl from_ => (.router m, [.send from_ (.reply m)])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.ModuleValue

