-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.NamedSend

open Leanactors


inductive Msg
  | emit
  | item (a0 : Nat)
  | flush
  deriving Repr, DecidableEq

inductive St
  | source (s : Nat)
  | sink (s : List Nat)
  deriving Repr, DecidableEq

/-- Registered name `Sink`. -/
def sink : Pid := 0

/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .source _ => false
    | .sink _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .emit

def beh : EBehavior St Msg
  | _, _, .source n, .emit => (.source (n + 1), [.send sink (.item n), .send sink .flush])
  | _, _, .sink _w0, .flush => (.sink [], [])
  | _, _, .sink xs, .item x => (.sink (xs ++ [x]), [])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.NamedSend

