-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Core

namespace Leanactors.Fixtures.NamedSend

open Leanactors


inductive Msg
  | emit
  | item (a0 : Nat)
  | flush
  deriving Repr, DecidableEq

inductive St
  | source (s : Nat)
  | sink (s : List Nat)
  deriving Repr, DecidableEq

/-- Registered name `Sink`. -/
def sink : Pid := 0

def beh : Behavior St Msg
  | _, .source n, .emit => (.source (n + 1), [(sink, .item n), (sink, .flush)])
  | _, .sink _w0, .flush => (.sink [], [])
  | _, .sink xs, .item x => (.sink (xs ++ [x]), [])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, s, _ => (s, [])

end Leanactors.Fixtures.NamedSend

