-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Core

namespace Leanactors.Fixtures.NestedCalls

open Leanactors


inductive Msg
  | bump
  | get (caller : Pid)
  | reply (a0 : Nat)
  | probe
  deriving Repr, DecidableEq

inductive St
  | counter (s : Nat)
  | prober (s : Nat)
  | prober_await0 (acc : Nat)
  | prober_await1 (a : Nat) (acc : Nat)
  deriving Repr, DecidableEq

/-- Registered name `Counter`. -/
def counter : Pid := 0

def beh : Behavior St Msg
  | _, .counter n, .bump => (.counter (n + 1), [])
  | _, .counter n, .get from_ => (.counter n, [(from_, .reply n)])
  | me, .prober acc, .probe => (.prober_await0 acc, [(counter, .get me)])
  | _, .prober_await1 a acc, .reply b => (.prober ((acc + a) + b), [])
  | me, .prober_await1 a acc, m => (.prober_await1 a acc, [(me, m)])
  | me, .prober_await0 acc, .reply a => (.prober_await1 a acc, [(counter, .get me)])
  | me, .prober_await0 acc, m => (.prober_await0 acc, [(me, m)])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, s, _ => (s, [])

end Leanactors.Fixtures.NestedCalls

