-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.NestedCalls

open Leanactors


inductive Msg
  | bump
  | get (caller : Pid)
  | reply (a0 : Nat)
  | probe
  deriving Repr, DecidableEq

inductive St
  | counter (s : Nat)
  | prober (s : Nat)
  | prober_await0 (acc : Nat)
  | prober_await1 (a : Nat) (acc : Nat)
  deriving Repr, DecidableEq

/-- Registered name `Counter`. -/
def counter : Pid := 0

/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .counter _ => false
    | .prober _ => false
    | .prober_await0 _ => false
    | .prober_await1 _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .bump

def beh : EBehavior St Msg
  | _, _, .counter n, .bump => (.counter (n + 1), [])
  | _, _, .counter n, .get from_ => (.counter n, [.send from_ (.reply n)])
  | me, _, .prober acc, .probe => (.prober_await0 acc, [.send counter (.get me)])
  | _, _, .prober_await1 a acc, .reply b => (.prober ((acc + a) + b), [])
  | me, _, .prober_await1 a acc, m => (.prober_await1 a acc, [.send me m])
  | me, _, .prober_await0 acc, .reply a => (.prober_await1 a acc, [.send counter (.get me)])
  | me, _, .prober_await0 acc, m => (.prober_await0 acc, [.send me m])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.NestedCalls

