-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys
import Leanactors.Term

namespace Leanactors.Fixtures.NoState

open Leanactors

inductive Reply
  | ok
  deriving Repr, DecidableEq

inductive Msg
  | put (a0 : Term)
  | forget
  | swap (caller : Pid)
  | reply (a0 : Reply)
  | ping
  deriving Repr, DecidableEq

inductive St
  | cache (entries : Term) (last : Term)
  | ping (s : Term)
  deriving Repr, DecidableEq

/-- Registered name `Cache`. -/
def cache : Pid := 0

/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .cache _ _ => false
    | .ping _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .forget

def beh : EBehavior St Msg
  | _, _, .cache es _, .put v => (.cache es v, [])
  | _, _, .cache entries _, .forget => (.cache entries entries, [])
  | _, _, .cache es l, .swap from_ => (.cache l es, [.send from_ (.reply .ok)])
  | _, _, .ping s, .ping => (.ping s, [])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.NoState

