-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Core

namespace Leanactors.Fixtures.Nonlinear

open Leanactors


inductive Msg
  | claim (a0 : Pid)
  | drop (a0 : Pid)
  deriving Repr, DecidableEq

inductive St
  | owner (s : Option Pid)
  deriving Repr, DecidableEq


def beh : Behavior St Msg
  | _, .owner none, .claim p => (.owner (some p), [])
  | _, .owner (some p'), .drop p => if p = p' then (.owner none, []) else (.owner (some p'), [])
  | _, .owner s, _ => (.owner s, [])

end Leanactors.Fixtures.Nonlinear

