-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.Nonlinear

open Leanactors


inductive Msg
  | claim (a0 : Pid)
  | drop (a0 : Pid)
  deriving Repr, DecidableEq

inductive St
  | owner (s : Option Pid)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .owner _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun p _ => .claim p

def beh : EBehavior St Msg
  | _, _, .owner none, .claim p => (.owner (some p), [])
  | _, _, .owner (some p'), .drop p => if p = p' then (.owner none, []) else (.owner (some p'), [])
  | _, _, .owner s, _ => (.owner s, [])

end Leanactors.Fixtures.Nonlinear

