-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Core

namespace Leanactors.Fixtures.PidNarrow

open Leanactors


inductive Msg
  | attach (a0 : Pid)
  | kick
  | detach
  | go
  deriving Repr, DecidableEq

inductive St
  | ref (s : Option Pid)
  | target (s : Nat)
  deriving Repr, DecidableEq


def beh : Behavior St Msg
  | _, .ref _w0, .attach p => (.ref (some p), [])
  | _, .ref (some w), .kick => (.ref (some w), [(w, .go)])
  | _, .ref _w0, .detach => (.ref none, [])
  | _, .ref s, _ => (.ref s, [])
  | _, .target n, .go => (.target (n + 1), [])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, s, _ => (s, [])

end Leanactors.Fixtures.PidNarrow

