-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.PidNarrow

open Leanactors


inductive Msg
  | attach (a0 : Pid)
  | kick
  | detach
  | go
  deriving Repr, DecidableEq

inductive St
  | ref (s : Option Pid)
  | target (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .ref _ => false
    | .target _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .kick

def beh : EBehavior St Msg
  | _, _, .ref _w0, .attach p => (.ref (some p), [])
  | _, _, .ref (some w), .kick => (.ref (some w), [.send w .go])
  | _, _, .ref _w0, .detach => (.ref none, [])
  | _, _, .ref s, _ => (.ref s, [])
  | _, _, .target n, .go => (.target (n + 1), [])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.PidNarrow

