-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.Pipeline

open Leanactors


inductive Msg
  | add (a0 : Int)
  | trim
  | top (caller : Pid)
  | reply (a0 : List Int)
  deriving Repr, DecidableEq

inductive St
  | pipes (s : List Int)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .pipes _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .trim

def beh : EBehavior St Msg
  | _, _, .pipes l, .add n => (.pipes (l ++ [n]), [])
  | _, _, .pipes l, .trim => (.pipes (List.take 3 (List.reverse (List.filter (fun x => (x > 0)) l))), [])
  | _, _, .pipes l, .top from_ => (.pipes l, [.send from_ (.reply (List.take 1 (List.reverse l)))])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.Pipeline

