-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.ProcessExit

open Leanactors


inductive Msg
  | kill (a0 : Pid)
  | halt (a0 : Pid)
  deriving Repr, DecidableEq

inductive St
  | killer (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .killer _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .kill 0

def beh : EBehavior St Msg
  | _, _, .killer n, .kill p => (.killer (n + 1), [.signal p .error])
  | _, _, .killer n, .halt p => (.killer n, [.signal p .normal])

end Leanactors.Fixtures.ProcessExit

