-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.PubsubRoot

open Leanactors


inductive Msg
  | tick (a0 : Nat)
  | stop
  deriving Repr, DecidableEq

inductive St
  | ticker (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .ticker _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .stop

def beh : EBehavior St Msg
  | _, _, .ticker n, .tick k => (.ticker (n + k), [])
  | me, _, .ticker n, .stop => (.ticker n, [.unsubscribe me "ticks"])

end Leanactors.Fixtures.PubsubRoot

