-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.Pubsub

open Leanactors


inductive Msg
  | open
  | publish (a0 : Nat)
  | quiet
  | item (a0 : Nat)
  | alert
  | more
  deriving Repr, DecidableEq

inductive St
  | hub (f0 : Option Pid) (f1 : Nat)
  | reader (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .hub _ _ => false
    | .reader _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .open

def beh : EBehavior St Msg
  | _, fresh, .hub none n, .open => (.hub (some fresh) n, [.spawnLink (.reader 0), .subscribe fresh "news", .subscribe fresh "alerts"])
  | _, _, .hub r n, .publish k => (.hub r (n + k), [.broadcast "news" (.item k), .broadcast "alerts" .alert])
  | me, _, .hub s_0 s_1, .quiet => (.hub s_0 s_1, [.unsubscribe me "alerts"])
  | _, _, .hub s_0 s_1, _ => (.hub s_0 s_1, [])
  | _, _, .reader n, .item k => (.reader (n + k), [])
  | me, _, .reader n, .alert => (.reader n, [.unsubscribe me "alerts"])
  | me, _, .reader n, .more => (.reader n, [.subscribe me "news"])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.Pubsub

