-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.Queue

open Leanactors

inductive Reply
  | n (a0 : Nat)
  | head (a0 : Nat)
  | empty
  deriving Repr, DecidableEq

inductive Msg
  | push (a0 : Nat)
  | pop
  | clear
  | size (caller : Pid)
  | front (caller : Pid)
  | serve (caller : Pid)
  | reply (a0 : Reply)
  deriving Repr, DecidableEq

inductive St
  | fifo (f0 : List Nat) (f1 : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .fifo _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .pop

def beh : EBehavior St Msg
  | _, _, .fifo q served, .push x => (.fifo (q ++ [x]) served, [])
  | _, _, .fifo q0 served, .pop => (let q := List.tail q0; (.fifo q served, []))
  | _, _, .fifo _ served, .clear => (.fifo [] served, [])
  | _, _, .fifo q served, .size from_ => if List.isEmpty q then (.fifo q served, [.send from_ (.reply .empty)]) else (.fifo q served, [.send from_ (.reply (.n (List.length q + List.length q)))])
  | _, _, .fifo q served, .front from_ => (match List.head? q with | (some x) => (.fifo q served, [.send from_ (.reply (.head x))]) | none => (.fifo q served, [.send from_ (.reply .empty)]))
  | _, _, .fifo q0 served, .serve from_ => (match q0 with | (x :: rest) => (.fifo rest (served + 1), [.send from_ (.reply (.head x))]) | [] => (.fifo [] served, [.send from_ (.reply .empty)]))
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.Queue

