-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.ReceiveAfter

open Leanactors


inductive Msg
  | set (a0 : Nat)
  | stop
  | ping
  | after_run (a0 : Nat)
  | go
  deriving Repr, DecidableEq

inductive St
  | ticker (s : Nat) (gen : Nat)
  | boss (s : Option Pid)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .ticker _ _ => false
    | .boss _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .stop

def beh : EBehavior St Msg
  | me, _, .ticker n gen, m@(.set x) => if (x > n) then (.ticker x (gen + 1), [.sendAfter me (.after_run (gen + 1))]) else (.ticker n (gen + 1), [.send me m, .sendAfter me (.after_run (gen + 1))])
  | _, _, .ticker n gen, .stop => (.ticker n gen, [.exit .normal])
  | me, _, .ticker n gen, .after_run gen' => if gen' = gen then (.ticker (n + 1) (gen + 1), [.sendAfter me (.after_run (gen + 1))]) else (.ticker n gen, [])
  | me, _, .ticker s_0 gen, m => (.ticker s_0 (gen + 1), [.send me m, .sendAfter me (.after_run (gen + 1))])
  | _, fresh, .boss _w0, .go => (.boss (some fresh), [.spawn (.ticker 0 0), .sendAfter fresh (.after_run 0)])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.ReceiveAfter

