-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys
import Leanactors.AssocList
import Leanactors.Term

namespace Leanactors.Fixtures.RecordState

open Leanactors


inductive Msg
  | push (a0 : Term) (a1 : Term)
  | pop (a0 : Term)
  | halt
  | size (caller : Pid)
  | done (caller : Pid)
  | reply (a0 : Nat)
  deriving Repr, DecidableEq

inductive St
  | jobs (queue : List (Term × Term)) (running : Bool) (done : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .jobs _ _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .halt

def beh : EBehavior St Msg
  | _, _, .jobs queue _ done, .push id job => (.jobs (AssocList.insert queue id job) true done, [])
  | _, _, .jobs queue running done, .pop id => (match AssocList.get? queue id with | none => (.jobs queue running done, []) | (some _) => (.jobs (AssocList.erase queue id) running (done + 1), []))
  | _, _, .jobs queue true done, .halt => (.jobs queue false done, [])
  | _, _, .jobs queue running done, .halt => (.jobs queue running done, [])
  | _, _, .jobs q running done, .size from_ => (.jobs q running done, [.send from_ (.reply (AssocList.size q))])
  | _, _, .jobs queue running done, .done from_ => (.jobs queue running done, [.send from_ (.reply done)])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.RecordState

