-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys
import Leanactors.Term

namespace Leanactors.Fixtures.ReplyExprType

open Leanactors


inductive Msg
  | push (a0 : Term)
  | all (caller : Pid)
  | recent (caller : Pid)
  | reply (a0 : List Term)
  deriving Repr, DecidableEq

inductive St
  | ring (entries : List Term) (cap : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .ring _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .push (Term.mk 0)

def beh : EBehavior St Msg
  | _, _, .ring state_0 state_1, .all from_ => (.ring state_0 state_1, [.send from_ (.reply state_0)])
  | _, _, .ring state_0 state_1, .recent from_ => (.ring state_0 state_1, [.send from_ (.reply (List.take 2 state_0))])
  | _, _, .ring state_0 state_1, .push x => if (List.length state_0 ≥ state_1) then (let rest := List.tail state_0; (.ring (rest ++ [x]) state_1, [])) else (.ring (state_0 ++ [x]) state_1, [])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.ReplyExprType

