-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.ReplyLater

open Leanactors

inductive Reply
  | go
  deriving Repr, DecidableEq

inductive Msg
  | release
  | wait (caller : Pid)
  | reply (a0 : Reply)
  deriving Repr, DecidableEq

inductive St
  | waiter (s : Option Pid)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .waiter _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .release

def beh : EBehavior St Msg
  | _, _, .waiter none, .wait from_ => (.waiter (some from_), [])
  | _, _, .waiter w, .wait from_ => (.waiter w, [.send from_ (.reply .go)])
  | _, _, .waiter (some w), .release => (.waiter none, [.send w (.reply .go)])
  | _, _, .waiter s_0, .release => (.waiter s_0, [.exit .error])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.ReplyLater

