-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Core

namespace Leanactors.Fixtures.ReplyLater

open Leanactors

inductive Reply
  | go
  deriving Repr, DecidableEq

inductive Msg
  | release
  | wait (caller : Pid)
  | reply (a0 : Reply)
  deriving Repr, DecidableEq

inductive St
  | waiter (s : Option Pid)
  deriving Repr, DecidableEq


def beh : Behavior St Msg
  | _, .waiter none, .wait from_ => (.waiter (some from_), [])
  | _, .waiter w, .wait from_ => (.waiter w, [(from_, .reply .go)])
  | _, .waiter (some w), .release => (.waiter none, [(w, .reply .go)])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, s, _ => (s, [])

end Leanactors.Fixtures.ReplyLater

