-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.ReplyTimeout

open Leanactors


inductive Msg
  | timeout
  | nap
  | touch (caller : Pid)
  | peek (caller : Pid)
  | reply (a0 : Nat)
  deriving Repr, DecidableEq

inductive St
  | session (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .session _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .timeout

def beh : EBehavior St Msg
  | me, _, .session n, .touch from_ => (.session (n + 1), [.send from_ (.reply n), .sendAfter me .timeout])
  | _, _, .session n, .peek from_ => (.session n, [.send from_ (.reply n)])
  | _, _, .session n, .nap => (.session n, [])
  | _, _, .session _w0, .timeout => (.session 0, [])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.ReplyTimeout

