-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.SendAfter

open Leanactors


inductive Msg
  | arm
  | ring
  | remind (a0 : Pid)
  deriving Repr, DecidableEq

inductive St
  | alarm (s : Bool)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .alarm _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .arm

def beh : EBehavior St Msg
  | me, _, .alarm false, .arm => (.alarm true, [.sendAfter me .ring])
  | _, _, .alarm _w0, .ring => (.alarm false, [])
  | _, _, .alarm s, .remind p => (.alarm s, [.sendAfter p .ring])
  | _, _, .alarm s, _ => (.alarm s, [])

end Leanactors.Fixtures.SendAfter

