-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.SpawnMonitor

open Leanactors


inductive Msg
  | hire
  | DOWN (a0 : Pid) (a1 : Reason)
  | work
  | quit
  deriving Repr, DecidableEq

inductive St
  | boss (f0 : Option Pid) (f1 : Nat)
  | hand (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .boss _ _ => false
    | .hand _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .hire
  downMsg := some fun p r => .DOWN p r

def beh : EBehavior St Msg
  | _, fresh, .boss none k, .hire => (.boss (some fresh) k, [.spawnMonitor (.hand 0)])
  | _, _, .boss (some p') k, .DOWN p _w0 => if p = p' then (.boss none (k + 1), []) else (.boss (some p') k, [])
  | _, _, .boss s_0 s_1, _ => (.boss s_0 s_1, [])
  | _, _, .hand n, .work => (.hand (n + 1), [])
  | _, _, .hand n, .quit => (.hand n, [.exit .normal])
  | me, _, .hand s_0, m => (.hand s_0, [.send me m])

end Leanactors.Fixtures.SpawnMonitor

