-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.StopReply

open Leanactors

inductive Reply
  | bye
  deriving Repr, DecidableEq

inductive Msg
  | close (caller : Pid)
  | slam (caller : Pid)
  | reply (a0 : Reply)
  deriving Repr, DecidableEq

inductive St
  | door (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .door _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun p _ => .close p

def beh : EBehavior St Msg
  | _, _, .door n, .close from_ => (.door n, [.send from_ (.reply .bye), .exit .normal])
  | _, _, .door n, .slam from_ => (.door (n + 1), [.send from_ (.reply .bye), .exit .error])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.StopReply

