-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.StopKill

open Leanactors


inductive Msg
  | quit
  | shut (a0 : Pid)
  | work
  | die
  deriving Repr, DecidableEq

inductive St
  | boss (s : Nat)
  | grunt (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .boss _ => false
    | .grunt _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .quit

def beh : EBehavior St Msg
  | _, _, .boss n, .quit => (.boss n, [.exit .kill])
  | _, _, .boss n, .shut p => (.boss n, [.signal p .error])
  | _, _, .grunt n, .work => (.grunt (n + 1), [])
  | _, _, .grunt n, .die => (.grunt n, [.exit .kill])
  | me, _, .grunt s_0, m => (.grunt s_0, [.send me m])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.StopKill

