-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys
import Leanactors.Str

namespace Leanactors.Fixtures.Strings

open Leanactors


inductive Msg
  | greet (a0 : String)
  | suffix (a0 : String)
  | clear
  | render (caller : Pid)
  | shout (caller : Pid)
  | reply (a0 : String)
  deriving Repr, DecidableEq

inductive St
  | greeter (name : String) (suffix : String) (greeted : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .greeter _ _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .clear

def beh : EBehavior St Msg
  | _, _, .greeter name suffix greeted, .greet "" => (.greeter name suffix greeted, [])
  | _, _, .greeter _ suffix greeted, .greet n => (.greeter n suffix (greeted + 1), [])
  | _, _, .greeter name suffix greeted, .suffix x => (.greeter name (suffix ++ x) greeted, [])
  | _, _, .greeter name _ greeted, .clear => (.greeter name "" greeted, [])
  | _, _, .greeter name suffix greeted, .render from_ => (.greeter name suffix greeted, [.send from_ (.reply ("hello, " ++ name ++ "!" ++ suffix))])
  | _, _, .greeter name suffix greeted, .shout from_ => (.greeter name suffix greeted, [.send from_ (.reply (name ++ " (" ++ Str.toStr greeted ++ " times)"))])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.Strings

