-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.Structs

open Leanactors

inductive Tag
  | origin
  | other
  deriving Repr, DecidableEq

structure Point where
  x : Nat := 0
  y : Nat := 0
  tag : Tag := .origin
  deriving Repr, DecidableEq

inductive Reply
  | at (a0 : Point)
  | moves (a0 : Nat)
  deriving Repr, DecidableEq

inductive Msg
  | move (a0 : Point)
  | home
  | pos (caller : Pid)
  | count (caller : Pid)
  | reply (a0 : Reply)
  deriving Repr, DecidableEq

inductive St
  | board (cur : Point) (moves : Nat) (width : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .board _ _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .home

def beh : EBehavior St Msg
  | _, _, .board _state_0 state_1 state_2, .move p@⟨0, _w0, _w1⟩ => (.board p (state_1 + 1) state_2, [])
  | _, _, .board state_0 state_1 state_2, .move ⟨x, y, _w0⟩ => if (x < 3) then (.board ({ x := x, y := y, tag := .other } : Point) (state_1 + 1) state_2, []) else (.board state_0 (state_1 + 1) state_2, [])
  | _, _, .board _state_0 state_1 state_2, .home => (.board ({} : Point) state_1 state_2, [])
  | _, _, .board c state_1 state_2, .pos from_ => (.board c state_1 state_2, [.send from_ (.reply (.at c))])
  | _, _, .board state_0 state_1 state_2, .count from_ => (.board state_0 state_1 state_2, [.send from_ (.reply (.moves (state_1 + state_2)))])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.Structs

