-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.Timeout

open Leanactors


inductive Msg
  | poke
  | timeout
  deriving Repr, DecidableEq

inductive St
  | idle (s : Nat)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .idle _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .poke

def beh : EBehavior St Msg
  | me, _, .idle n, .poke => (.idle n, [.sendAfter me .timeout])
  | _, _, .idle n, .timeout => (.idle (n + 1), [])

end Leanactors.Fixtures.Timeout

