-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys
import Leanactors.Term

namespace Leanactors.Fixtures.Untyped

open Leanactors

inductive Reply
  | empty
  | ok1 (a0 : Term)
  | ok
  deriving Repr, DecidableEq

inductive Msg
  | ping
  | write (a0 : Term)
  | clear
  | flushed
  | head (caller : Pid)
  | drop (caller : Pid) (a1 : Term)
  | reply (a0 : Reply)
  deriving Repr, DecidableEq

inductive St
  | log (f0 : Option Term) (f1 : Bool)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .log _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .ping

def beh : EBehavior St Msg
  | me, _, .log _ dirty, .write line => (.log (some line) dirty, [.send me .flushed, .send me .ping])
  | _, _, .log _ _, .clear => (.log none false, [])
  | _, _, .log last dirty, .head from_ => (match last with | none => (.log last dirty, [.send from_ (.reply .empty)]) | (some l) => (.log last dirty, [.send from_ (.reply (.ok1 l))]))
  | _, _, .log _ dirty, .drop from_ _ => (.log none dirty, [.send from_ (.reply .ok)])
  | _, _, .log last _, .flushed => (.log last true, [])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.Untyped

