-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Sys

namespace Leanactors.Fixtures.Wildcards

open Leanactors


inductive Msg
  | pair (a0 : Nat) (a1 : Nat)
  | zero
  | peek (caller : Pid)
  | reply (a0 : Nat)
  deriving Repr, DecidableEq

inductive St
  | wild (f0 : Nat) (f1 : Nat) (f2 : Option Pid)
  deriving Repr, DecidableEq


/-- Who traps exits (from `Process.flag(:trap_exit, true)`), the EXIT message, the DOWN message. -/
def sig : Signals St Msg where
  traps := fun
    | .wild _ _ _ => false
  -- no module declares {:EXIT, ...}; nobody traps, so this codec is never used
  exitMsg := fun _ _ => .zero

def beh : EBehavior St Msg
  | _, _, .wild _w1 c _w2, .pair a _w0 => if (a > c) then (.wild a c none, []) else (.wild 0 0 none, [])
  | _, _, .wild _ _ _, .zero => (.wild 0 0 none, [])
  | _, _, .wild a _w0 _w1, .peek from_ => (.wild a 0 none, [.send from_ (.reply a)])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, _, s, _ => (s, [])

end Leanactors.Fixtures.Wildcards

