-- GENERATED by elixir/to_lean.exs. Do not edit.
import Leanactors.Core

namespace Leanactors.Fixtures.Wildcards

open Leanactors


inductive Msg
  | pair (a0 : Nat) (a1 : Nat)
  | zero
  | peek (caller : Pid)
  | reply (a0 : Nat)
  deriving Repr, DecidableEq

inductive St
  | wild (f0 : Nat) (f1 : Nat) (f2 : Option Pid)
  deriving Repr, DecidableEq


def beh : Behavior St Msg
  | _, .wild _w1 c _w2, .pair a _w0 => if (a > c) then (.wild a c none, []) else (.wild 0 0 none, [])
  | _, .wild _ _ _, .zero => (.wild 0 0 none, [])
  | _, .wild a _w0 _w1, .peek from_ => (.wild a 0 none, [(from_, .reply a)])
  -- Unmatched message: GenServer would crash (cast) or ignore (info). Modelled as ignore.
  | _, s, _ => (s, [])

end Leanactors.Fixtures.Wildcards

